package org.dcm4chee.xds.infoset.v30.ws;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DocumentRegistry_Service", targetNamespace = "urn:ihe:iti:xds-b:2007", wsdlLocation = "/wsdl/registry.wsdl")
public class DocumentRegistryService
    extends Service
{
	private final static URL DOCUMENTREGISTRYSERVICE_WSDL_LOCATION;

    static {
    	DOCUMENTREGISTRYSERVICE_WSDL_LOCATION = DocumentRegistryService.class.getResource("/wsdl/registry.wsdl");
    }

    public DocumentRegistryService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DocumentRegistryService() {
        super(DOCUMENTREGISTRYSERVICE_WSDL_LOCATION, new QName("urn:ihe:iti:xds-b:2007", "DocumentRegistry_Service"));
    }

    /**
     * 
     * @return
     *     returns DocumentRegistryPortType
     */
    @WebEndpoint(name = "DocumentRegistry_Port_Soap11")
    public DocumentRegistryPortType getDocumentRegistryPortSoap11() {
        return (DocumentRegistryPortType)super.getPort(new QName("urn:ihe:iti:xds-b:2007", "DocumentRegistry_Port_Soap11"), DocumentRegistryPortType.class);
    }

    /**
     * 
     * @return
     *     returns DocumentRegistryPortType
     */
    @WebEndpoint(name = "DocumentRegistry_Port_Soap12")
    public DocumentRegistryPortType getDocumentRegistryPortSoap12() {
        return (DocumentRegistryPortType)super.getPort(new QName("urn:ihe:iti:xds-b:2007", "DocumentRegistry_Port_Soap12"), DocumentRegistryPortType.class);
    }

}
